services:
  mysql:
    image: arm64v8/mysql:oracle
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "yellowcard"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    platform: linux/amd64
    build:
      dockerfile: docker/Api.Dockerfile
      context: .
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      NODE_ENV: development
    ports:
      - 4000:4000
    depends_on:
      - mysql
    command: npm run start
    volumes:
      - ./:/usr/src/app

volumes:
  mysql-data:
